#!/bin/bash

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Create temp directory and ensure cleanup
TEMP_DIR=$(mktemp -d)
trap 'rm -rf "$TEMP_DIR"' EXIT

echo "==> Testing easel installation"

# Create test alignment file
echo "-> Creating test alignment file"
cat > "${TEMP_DIR}/test.afa" << 'EOF'
>MYG_PHYCA
--------V-LSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDRFKHLKT
EAEMKASEDLKKHGVTVLTALGAILKKKGH---HEAELKPLAQSHATKHKIPIKYLEFIS
EAIIHVLHSRHPGDFGADAQGAMNKALELFRKDIAAKYKELGYQG
>GLB5_PETMA
PIVDTGSVAPLSAAEKTKIRSAWAPVYSTYETSGVDILVKFFTSTPAAQEFFPKFKGLTT
ADQLKKSADVRWHAERIINAVNDAVASMDDTEKMSMKLRDLSGKHAKSFQVDPQYFKVLA
AVI---------ADTVAAGDAGFEKLMSMICILLRSAY-------
>HBB_HUMAN
--------VHLTPEEKSAVTALWGKV--NVDEVGGEALGRLLVVYPWTQRFFESFGDLST
PDAVMGNPKVKAHGKKVLGAFSDGLAHLDN---LKGTFATLSELHCDKLHVDPENFRLLG
NVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH------
>HBA_HUMAN
--------V-LSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHF-----
-DLSHGSAQVKGHGKKVADALTNAVAHVDD---MPNALSALSDLHAHKLRVDPVNFKLLS
HCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR------
EOF

# Test esl-alistat
echo "-> Testing esl-alistat"
ALISTAT_OUTPUT=$($(cbp prefix bin)/esl-alistat "${TEMP_DIR}/test.afa")

if echo "$ALISTAT_OUTPUT" | grep -q "Alignment length:    165"; then
    echo "Test PASSED"
    exit 0
else
    echo "Test FAILED"
    echo "Expected 'Alignment length:    165' in output"
    echo "Got: $ALISTAT_OUTPUT"
    exit 1
fi
