#!/bin/bash

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

echo "==> Testing ${PROJ} installation"

# Create test alignment file
echo "-> Creating test alignment file"
cat > "test.afa" << 'EOF'
>MYG_PHYCA
--------V-LSEGEWQLVLHVWAKVEADVAGHGQDILIRLFKSHPETLEKFDRFKHLKT
EAEMKASEDLKKHGVTVLTALGAILKKKGH---HEAELKPLAQSHATKHKIPIKYLEFIS
EAIIHVLHSRHPGDFGADAQGAMNKALELFRKDIAAKYKELGYQG
>GLB5_PETMA
PIVDTGSVAPLSAAEKTKIRSAWAPVYSTYETSGVDILVKFFTSTPAAQEFFPKFKGLTT
ADQLKKSADVRWHAERIINAVNDAVASMDDTEKMSMKLRDLSGKHAKSFQVDPQYFKVLA
AVI---------ADTVAAGDAGFEKLMSMICILLRSAY-------
>HBB_HUMAN
--------VHLTPEEKSAVTALWGKV--NVDEVGGEALGRLLVVYPWTQRFFESFGDLST
PDAVMGNPKVKAHGKKVLGAFSDGLAHLDN---LKGTFATLSELHCDKLHVDPENFRLLG
NVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH------
>HBA_HUMAN
--------V-LSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHF-----
-DLSHGSAQVKGHGKKVADALTNAVAHVDD---MPNALSALSDLHAHKLRVDPVNFKLLS
HCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR------
EOF

# Test esl-alistat
echo "-> Testing esl-alistat"
ALISTAT_OUTPUT=$($(cbp prefix bin)/esl-alistat "test.afa")

assert 'echo "${ALISTAT_OUTPUT}" | grep -q "Alignment length:    165"' \
    "Expected 'Alignment length:    165' in output"
