#!/bin/bash

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

echo "==> Testing ${PROJ} installation"

# Test pip compile
echo "-> Testing uv pip compile"
cat > "requirements.in" << 'EOF'
requests
EOF

COMPILED=$($(cbp prefix bin)/uv pip compile -q "requirements.in")

assert 'echo "${COMPILED}" | grep -q "This file was autogenerated by uv"' \
    "Missing autogeneration comment"

assert 'echo "${COMPILED}" | grep -q "# via requests"' \
    "Missing dependency comment"

# Test uvx version check
echo "-> Testing uvx version check"
VERSION_OUTPUT=$(uvx -q ruff@0.5.1 --version)

assert 'echo "${VERSION_OUTPUT}" | grep -q "ruff 0.5.1"' \
    "Incorrect ruff version"
