#!/bin/bash

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Create temp directory and ensure cleanup
TEMP_DIR=$(mktemp -d)
trap 'rm -rf "$TEMP_DIR"' EXIT

echo "==> Testing uv installation"

# Test pip compile
echo "-> Testing uv pip compile"
cat > "${TEMP_DIR}/requirements.in" << 'EOF'
requests
EOF

COMPILED=$($(cbp prefix bin)/uv pip compile -q "${TEMP_DIR}/requirements.in")

if ! echo "$COMPILED" | grep -q "This file was autogenerated by uv"; then
    echo "Test FAILED: Missing autogeneration comment"
    exit 1
fi

if ! echo "$COMPILED" | grep -q "# via requests"; then
    echo "Test FAILED: Missing dependency comment"
    exit 1
fi

# Test uvx version check
echo "-> Testing uvx version check"
VERSION_OUTPUT=$(uvx -q ruff@0.5.1 --version)

if ! echo "$VERSION_OUTPUT" | grep -q "ruff 0.5.1"; then
    echo "Test FAILED: Incorrect ruff version"
    exit 1
fi

echo "Test PASSED"
exit 0
