name: Test Binaries

on:
  release:
    types: [edited]
  schedule:
    - cron: '0 0 * * *'  # Run daily
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/test-binaries.yml'
      - 'test-binaries/**'

jobs:
  test-packages:
    # Only run when Binaries release is updated
    if: ${{ github.event_name != 'release' || github.event.release.tag_name == 'Binaries' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            cbp_bin: cbp.linux
          - os: macos-latest
            cbp_bin: cbp.macos
          - os: windows-latest
            cbp_bin: cbp.windows.exe

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download cbp
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            curl.exe -LO https://github.com/wang-q/cbp/releases/latest/download/${{ matrix.cbp_bin }}
          else
            curl -LO https://github.com/wang-q/cbp/releases/latest/download/${{ matrix.cbp_bin }}
            chmod +x ${{ matrix.cbp_bin }}
          fi
        shell: bash

      - name: Initialize cbp
        run: |
          ./${{ matrix.cbp_bin }} init
          if [ "$RUNNER_OS" == "Windows" ]; then
            echo "$HOME/.cbp/bin" >> $GITHUB_PATH
          else
            echo "$HOME/.cbp/bin" >> $GITHUB_PATH
            source ~/.bashrc
          fi
        shell: bash

      - name: Test cbp installation
        run: cbp --version || exit 1
        shell: bash

      - name: Install and test packages
        run: |
          platform=$(echo "$RUNNER_OS" | tr '[:upper:]' '[:lower:]')
          echo "==> Current platform: $platform"

          # Get all packages and platform-specific available packages with retry
          max_attempts=5
          attempt=1
          while [ $attempt -le $max_attempts ]; do
            echo "==> Attempt $attempt of $max_attempts to get package lists"
            if all_pkgs=$(cbp avail 2>/dev/null | grep -v "^==>" | tr -s '[:space:]' '\n' | grep -v '^$' | sed 's/[[:space:]]*$//' ) && \
               platform_pkgs=$(cbp avail $platform 2>/dev/null | grep -v "^==>" | tr -s '[:space:]' '\n' | grep -v '^$' | sed 's/[[:space:]]*$//' ) && \
               [ -n "$all_pkgs" ] && [ -n "$platform_pkgs" ]; then
              break
            fi
            echo "==> Failed attempt $attempt, waiting 30 seconds before retry..."
            sleep 30
            attempt=$((attempt + 1))
          done

          if [ $attempt -gt $max_attempts ]; then
            echo "Error: Failed to get package lists after $max_attempts attempts"
            exit 1
          fi

          # Mark packages not available for current platform
          for pkg in $all_pkgs; do
            if ! echo "$platform_pkgs" | grep -q "^$pkg\$"; then
              skipped_unavailable="${skipped_unavailable:-} $pkg"
            fi
          done

          test_results_pass=""
          test_results_fail=""

          # Test available packages
          for pkg in $platform_pkgs; do
            echo "Testing $pkg..."
            if [ -f "test-binaries/$pkg.sh" ]; then
              # Use package-specific test script if available
              if cbp install $pkg && \
                 bash "test-binaries/$pkg.sh"; then
                test_results_pass="${test_results_pass:+$test_results_pass }$pkg"
              else
                test_results_fail="${test_results_fail}❌ Failed: $pkg\n"
              fi
            elif [ -f "packages/$pkg.json" ]; then
              # Fallback to generic test-package.sh if JSON has tests
              if cbp install $pkg && \
                 bash "test-binaries/test-package.sh" "$pkg"; then
                test_results_pass="${test_results_pass:+$test_results_pass }$pkg"
              else
                test_results_fail="${test_results_fail}❌ Failed: $pkg\n"
              fi
            else
              skipped_notest="${skipped_notest:-} $pkg"
            fi
          done

          echo -e "\n==> Test Summary:"
          [ -n "${test_results_pass}" ] && echo -e "✅ Passed: ${test_results_pass}"
          [ -n "${test_results_fail}" ] && echo -e "${test_results_fail}"
          [ -n "${skipped_unavailable:-}" ] && echo -e "⏭️ Skipped (not available):${skipped_unavailable}"
          [ -n "${skipped_notest:-}" ] && echo -e "⏭️ Skipped (no test):${skipped_notest}"

          if echo "$test_results" | grep -q "FAILED"; then
            exit 1
          fi
        shell: bash
